export const RESPONSE_DATA_REQUEST = "RESPONSE_DATA_REQUEST";
export const RESPONSE_DATA_SUCCESS = "RESPONSE_DATA_SUCCESS";
export const RESPONSE_DATA_FAIL = "RESPONSE_DATA_FAIL";

export const USER_DATA_REQUEST = "USER_DATA_REQUEST";
export const USER_DATA_SUCCESS = "USER_DATA_SUCCESS";
export const USER_DATA_FAIL = "USER_DATA_FAIL";